from pathlib import Path

from siliconcompiler import ASIC
from lambdalib import LambalibTechLibrary
from lambdapdk import LambdaLibrary, _LambdaPath
from lambdapdk.sky130 import Sky130PDK, _Sky130Data

# Timing corners, as (transistor model, temperature, core supply, IO supply).
#
# A consistent 3.3V-IO set apart from `fast`, which has to take the 5.50V IO
# corner: upstream characterises no fast corner at 3.60V, and 5v50 is the only
# IO supply any `ff` corner is offered at. For hold analysis it is the core-side
# model that matters, and a high IO supply is the conservative direction on the
# output path.
_IO_CORNERS = {
    'slow': ('ss', '100C', '1v60', '3v00'),
    'typical': ('tt', '025C', '1v80', '3v30'),
    'fast': ('ff', 'n40C', '1v95', '5v50'),
}

# Which cells upstream characterises, grouped by how it spells the corner.
# Every file is '<cell>_<models>_<temp>_<voltages>.lib', but the spelling varies:
# the signal cells name the core *and* the IO transistor model ('tt_tt'), the
# supply cells name one ('tt'), and those gating a second IO domain repeat its
# voltage. All three groups resolve for all three corners.
_CELLS_PAIRED_MODEL = (
    'sky130_ef_io__gpiov2_pad',
    'sky130_ef_io__gpiov2_pad_wrapped',
    'sky130_fd_io__top_amuxsplitv2',
    'sky130_fd_io__top_gpiov2',
    'sky130_fd_io__top_gpiovrefv2',
    'sky130_fd_io__top_vrefcapv2',
    'sky130_fd_io__top_xres4v2',
)

_CELLS_TWO_DOMAIN = (
    'sky130_ef_io__vccd_lvc_clamped3_pad',
    'sky130_ef_io__vccd_lvc_clamped_pad',
    'sky130_ef_io__vdda_hvc_clamped_pad',
    'sky130_ef_io__vddio_hvc_clamped_pad',
    'sky130_ef_io__vssa_hvc_clamped_pad',
    'sky130_ef_io__vssio_hvc_clamped_pad',
    'sky130_fd_io__top_ground_hvc_wpad',
    'sky130_fd_io__top_hvclampv2',
    'sky130_fd_io__top_power_hvc_wpad',
    'sky130_fd_io__top_power_lvc_wpad',
    'sky130_fd_io__top_pwrdetv2',
)

_CELLS_ONE_DOMAIN = (
    'sky130_ef_io__vssd_lvc_clamped3_pad',
    'sky130_ef_io__vssd_lvc_clamped_pad',
    'sky130_fd_io__top_analog_pad',
    'sky130_fd_io__top_ground_lvc_wpad',
    'sky130_fd_io__top_hvclamp',
    'sky130_fd_io__top_lvc_b2b',
    'sky130_fd_io__top_lvclamp',
    'sky130_fd_io__top_sio_macro',
)

# The analog pads and the connect slices carry no timing, so upstream ships them
# as one corner-independent stub library each, added to every corner.
_CELLS_STUBS = (
    'sky130_ef_io__analog_stubs',
    'slices_stubs',
)


def _corner_libs(corner):
    """Returns the liberty filenames making up one IO timing corner."""
    model, temp, core, io = _IO_CORNERS[corner]

    files = [f'{cell}_{model}_{model}_{temp}_{core}_{io}.lib'
             for cell in _CELLS_PAIRED_MODEL]
    files += [f'{cell}_{model}_{temp}_{core}_{io}_{io}.lib'
              for cell in _CELLS_TWO_DOMAIN]
    files += [f'{cell}_{model}_{temp}_{core}_{io}.lib'
              for cell in _CELLS_ONE_DOMAIN]
    files += [f'{cell}.lib' for cell in _CELLS_STUBS]
    return files


class Sky130_IOLibrary(LambdaLibrary, _Sky130Data):
    '''
    Skywater130 I/O library.
    '''
    def __init__(self):
        super().__init__()
        self.set_name("sky130io")

        self.add_asic_pdk(Sky130PDK())

        path_base = Path('lambdapdk', 'sky130', 'libs', "sky130io")

        # The 'ef' (Efabless) macros this library instantiates are generated by
        # open_pdks into the same directory as the 'fd' foundry cells, so both
        # come from the one sky130_fd_io archive.
        upstream_path = Path("sky130A", "libs.ref", "sky130_fd_io")

        with self.active_dataroot("sky130_fd_io"):
            # Real characterised timing, replacing the single hand-written stub
            # cell this library used to carry. 26 cells resolve at all three
            # corners; the rest of the library has no liberty upstream either.
            for corner in _IO_CORNERS:
                with self.active_fileset(f"models.timing.{corner}.nldm"):
                    for filename in _corner_libs(corner):
                        self.add_file(upstream_path / "lib" / filename)
                    self.add_asic_libcornerfileset(corner, "nldm")

        with self.active_dataroot("lambdapdk"):
            with self.active_fileset("models.physical"):
                # Vendored, not referenced: the upstream LEF leaves the bond pad
                # plate inside OBS on 25 of its macros, so a bond pad placed on
                # the plate reads as a short to the pad instance. This copy is
                # the upstream file at pdk_rev with that corrected -- regenerate
                # it with scripts/patch_sky130io_bondpads.py. See PATCHES.md.
                self.add_file(path_base / "lef" / "sky130_ef_io.lef")

        with self.active_dataroot("sky130_fd_io"):
            with self.active_fileset("models.physical"):
                # The three GDS are read as a set: upstream's wrapper GDS holds
                # only the wrapper cell and an empty placeholder for the macro it
                # wraps, which sky130_ef_io.gds supplies.
                self.add_file(upstream_path / "gds" / "sky130_ef_io.gds")
                self.add_file(upstream_path / "gds" / "sky130_fd_io.gds")
                self.add_file(upstream_path / "gds" / "sky130_ef_io__gpiov2_pad_wrapped.gds")
                self.add_asic_aprfileset()

            with self.active_fileset("rtl"):
                # sky130_ef_io.v defines all 36 'ef' modules, gpiov2_pad_wrapped
                # and analog_pad among them, so the separate models this library
                # used to vendor for those two are gone -- the 2023 ef_io.v did
                # not carry them, the current one does, and keeping both would
                # have been a duplicate module definition.
                self.add_file(upstream_path / "verilog" / "sky130_ef_io.v")
                self.add_file(upstream_path / "verilog" / "sky130_fd_io.v")

                # TODO defines?

        self.add_asic_celllist('filler', ['sky130_ef_io__com_bus_slice_1um',
                                          'sky130_ef_io__com_bus_slice_5um',
                                          'sky130_ef_io__com_bus_slice_10um',
                                          'sky130_ef_io__com_bus_slice_20um'])

        with self.active_dataroot("lambdapdk"):
            with self.active_fileset("models.blackbox"):
                self.add_file(path_base / "blackbox" / "sky130_ef_io.v")
                self.add_file(path_base / "blackbox" / "sky130_fd_io.v")
            self.add_yosys_blackbox_fileset("models.blackbox")


class Sky130Lambdalib_la_ioanalog(LambalibTechLibrary, _LambdaPath):
    def __init__(self):
        super().__init__("la_ioanalog", [Sky130_IOLibrary])
        self.set_name("sky130_la_ioanalog")

        # version
        self.package.set_version("v1")

        lib_path = Path("lambdapdk", "sky130", "libs", "sky130io")

        with self.active_dataroot("lambdapdk"):
            with self.active_fileset("rtl"):
                self.add_file(lib_path / "lambda" / "la_ioanalog.v")


class Sky130Lambdalib_la_iobidir(LambalibTechLibrary, _LambdaPath):
    def __init__(self):
        super().__init__("la_iobidir", [Sky130_IOLibrary])
        self.set_name("sky130_la_iobidir")

        # version
        self.package.set_version("v1")

        lib_path = Path("lambdapdk", "sky130", "libs", "sky130io")

        with self.active_dataroot("lambdapdk"):
            with self.active_fileset("rtl"):
                self.add_file(lib_path / "lambda" / "la_iobidir.v")


class Sky130Lambdalib_la_ioclamp(LambalibTechLibrary, _LambdaPath):
    def __init__(self):
        super().__init__("la_ioclamp", [Sky130_IOLibrary])
        self.set_name("sky130_la_ioclamp")

        # version
        self.package.set_version("v1")

        lib_path = Path("lambdapdk", "sky130", "libs", "sky130io")

        with self.active_dataroot("lambdapdk"):
            with self.active_fileset("rtl"):
                self.add_file(lib_path / "lambda" / "la_ioclamp.v")


class Sky130Lambdalib_la_iocorner(LambalibTechLibrary, _LambdaPath):
    def __init__(self):
        super().__init__("la_iocorner", [Sky130_IOLibrary])
        self.set_name("sky130_la_iocorner")

        # version
        self.package.set_version("v1")

        lib_path = Path("lambdapdk", "sky130", "libs", "sky130io")

        with self.active_dataroot("lambdapdk"):
            with self.active_fileset("rtl"):
                self.add_file(lib_path / "lambda" / "la_iocorner.v")


class Sky130Lambdalib_la_ioinput(LambalibTechLibrary, _LambdaPath):
    def __init__(self):
        super().__init__("la_ioinput", [Sky130_IOLibrary])
        self.set_name("sky130_la_ioinput")

        # version
        self.package.set_version("v1")

        lib_path = Path("lambdapdk", "sky130", "libs", "sky130io")

        with self.active_dataroot("lambdapdk"):
            with self.active_fileset("rtl"):
                self.add_file(lib_path / "lambda" / "la_ioinput.v")


class Sky130Lambdalib_la_iorxdiff(LambalibTechLibrary, _LambdaPath):
    def __init__(self):
        super().__init__("la_iorxdiff", [Sky130_IOLibrary])
        self.set_name("sky130_la_iorxdiff")

        # version
        self.package.set_version("v1")

        lib_path = Path("lambdapdk", "sky130", "libs", "sky130io")

        with self.active_dataroot("lambdapdk"):
            with self.active_fileset("rtl"):
                self.add_file(lib_path / "lambda" / "la_iorxdiff.v")


class Sky130Lambdalib_la_iotxdiff(LambalibTechLibrary, _LambdaPath):
    def __init__(self):
        super().__init__("la_iotxdiff", [Sky130_IOLibrary])
        self.set_name("sky130_la_iotxdiff")

        # version
        self.package.set_version("v1")

        lib_path = Path("lambdapdk", "sky130", "libs", "sky130io")

        with self.active_dataroot("lambdapdk"):
            with self.active_fileset("rtl"):
                self.add_file(lib_path / "lambda" / "la_iotxdiff.v")


class Sky130Lambdalib_la_iovdd(LambalibTechLibrary, _LambdaPath):
    def __init__(self):
        super().__init__("la_iovdd", [Sky130_IOLibrary])
        self.set_name("sky130_la_iovdd")

        # version
        self.package.set_version("v1")

        lib_path = Path("lambdapdk", "sky130", "libs", "sky130io")

        with self.active_dataroot("lambdapdk"):
            with self.active_fileset("rtl"):
                self.add_file(lib_path / "lambda" / "la_iovdd.v")


class Sky130Lambdalib_la_iovdda(LambalibTechLibrary, _LambdaPath):
    def __init__(self):
        super().__init__("la_iovdda", [Sky130_IOLibrary])
        self.set_name("sky130_la_iovdda")

        # version
        self.package.set_version("v1")

        lib_path = Path("lambdapdk", "sky130", "libs", "sky130io")

        with self.active_dataroot("lambdapdk"):
            with self.active_fileset("rtl"):
                self.add_file(lib_path / "lambda" / "la_iovdda.v")


class Sky130Lambdalib_la_iovddio(LambalibTechLibrary, _LambdaPath):
    def __init__(self):
        super().__init__("la_iovddio", [Sky130_IOLibrary])
        self.set_name("sky130_la_iovddio")

        # version
        self.package.set_version("v1")

        lib_path = Path("lambdapdk", "sky130", "libs", "sky130io")

        with self.active_dataroot("lambdapdk"):
            with self.active_fileset("rtl"):
                self.add_file(lib_path / "lambda" / "la_iovddio.v")


class Sky130Lambdalib_la_iovss(LambalibTechLibrary, _LambdaPath):
    def __init__(self):
        super().__init__("la_iovss", [Sky130_IOLibrary])
        self.set_name("sky130_la_iovss")

        # version
        self.package.set_version("v1")

        lib_path = Path("lambdapdk", "sky130", "libs", "sky130io")

        with self.active_dataroot("lambdapdk"):
            with self.active_fileset("rtl"):
                self.add_file(lib_path / "lambda" / "la_iovss.v")


class Sky130Lambdalib_la_iovssa(LambalibTechLibrary, _LambdaPath):
    def __init__(self):
        super().__init__("la_iovssa", [Sky130_IOLibrary])
        self.set_name("sky130_la_iovssa")

        # version
        self.package.set_version("v1")

        lib_path = Path("lambdapdk", "sky130", "libs", "sky130io")

        with self.active_dataroot("lambdapdk"):
            with self.active_fileset("rtl"):
                self.add_file(lib_path / "lambda" / "la_iovssa.v")


class Sky130Lambdalib_la_iovssio(LambalibTechLibrary, _LambdaPath):
    def __init__(self):
        super().__init__("la_iovssio", [Sky130_IOLibrary])
        self.set_name("sky130_la_iovssio")

        # version
        self.package.set_version("v1")

        lib_path = Path("lambdapdk", "sky130", "libs", "sky130io")

        with self.active_dataroot("lambdapdk"):
            with self.active_fileset("rtl"):
                self.add_file(lib_path / "lambda" / "la_iovssio.v")


class Sky130LambdaLib_IO(LambalibTechLibrary):
    @classmethod
    def alias(cls, project: ASIC):
        Sky130Lambdalib_la_ioanalog.alias(project)
        Sky130Lambdalib_la_iobidir.alias(project)
        Sky130Lambdalib_la_ioclamp.alias(project)
        Sky130Lambdalib_la_iocorner.alias(project)
        Sky130Lambdalib_la_ioinput.alias(project)
        Sky130Lambdalib_la_iorxdiff.alias(project)
        Sky130Lambdalib_la_iotxdiff.alias(project)
        Sky130Lambdalib_la_iovdd.alias(project)
        Sky130Lambdalib_la_iovdda.alias(project)
        Sky130Lambdalib_la_iovddio.alias(project)
        Sky130Lambdalib_la_iovss.alias(project)
        Sky130Lambdalib_la_iovssa.alias(project)
        Sky130Lambdalib_la_iovssio.alias(project)
