/* Generated by Yosys 0.37 (git sha1 a5c7f69ed, clang 14.0.0-1ubuntu1.1 -fPIC -Os) */

module la_clkicgor(clk, te, en, eclk);
  input clk;
  wire clk;
  output eclk;
  wire eclk;
  input en;
  wire en;
  wire en_stable;
  input te;
  wire te;
  wire \te_$_OR__A_Y ;
  sky130_fd_sc_hd__nand2b_1 _0_ (
    .A_N(clk),
    .B(en_stable),
    .Y(eclk)
  );
  sky130_fd_sc_hd__or2_0 _1_ (
    .A(te),
    .B(en),
    .X(\te_$_OR__A_Y )
  );
  sky130_fd_sc_hd__dlxtp_1 en_stable_sky130_fd_sc_hd__dlxtp_1_Q (
    .D(\te_$_OR__A_Y ),
    .GATE(clk),
    .Q(en_stable)
  );
endmodule
