/* Generated by Yosys 0.37 (git sha1 a5c7f69ed, clang 14.0.0-1ubuntu1.1 -fPIC -Os) */

module la_dffsqn(d, clk, nset, qn);
  input clk;
  wire clk;
  input d;
  wire d;
  input nset;
  wire nset;
  output qn;
  wire qn;
  wire \qn_$_DFF_PN0__Q_D ;
  sky130_fd_sc_hd__inv_1 _0_ (
    .A(d),
    .Y(\qn_$_DFF_PN0__Q_D )
  );
  sky130_fd_sc_hd__dfrtp_1 \qn_$_DFF_PN0__Q  (
    .CLK(clk),
    .D(\qn_$_DFF_PN0__Q_D ),
    .Q(qn),
    .RESET_B(nset)
  );
endmodule
