/* Generated by Yosys 0.37 (git sha1 a5c7f69ed, clang 14.0.0-1ubuntu1.1 -fPIC -Os) */

module la_dsync(clk, in, out);
  input clk;
  wire clk;
  input in;
  wire in;
  output out;
  wire out;
  wire \shiftreg[0] ;
  sky130_fd_sc_hd__dfxtp_1 \out_$_DFF_P__Q  (
    .CLK(clk),
    .D(\shiftreg[0] ),
    .Q(out)
  );
  sky130_fd_sc_hd__dfxtp_1 \shiftreg_$_DFF_P__Q  (
    .CLK(clk),
    .D(in),
    .Q(\shiftreg[0] )
  );
endmodule
