/* Generated by Yosys 0.37 (git sha1 a5c7f69ed, clang 14.0.0-1ubuntu1.1 -fPIC -Os) */

module la_pwrbuf(vdd, vss, a, z);
  input a;
  wire a;
  input vdd;
  wire vdd;
  input vss;
  wire vss;
  output z;
  wire z;
  sky130_fd_sc_hd__buf_4 _0_ (
    .A(a),
    .X(z)
  );
endmodule
