/* Generated by Yosys 0.37 (git sha1 a5c7f69ed, clang 14.0.0-1ubuntu1.1 -fPIC -Os) */

module la_tiehi(z);
  wire _0_;
  output z;
  wire z;
  sky130_fd_sc_hd__conb_1 _1_ (
    .HI(_0_)
  );
  sky130_fd_sc_hd__buf_4 _2_ (
    .A(_0_),
    .X(z)
  );
endmodule
