/* Generated by Yosys 0.37 (git sha1 a5c7f69ed, clang 14.0.0-1ubuntu1.1 -fPIC -Os) */

module la_buf(a, z);
  input a;
  wire a;
  output z;
  wire z;
  gf180mcu_fd_sc_mcu7t5v0__buf_4 _0_ (
    .I(a),
    .Z(z)
  );
endmodule
