/* Generated by Yosys 0.37 (git sha1 a5c7f69ed, clang 14.0.0-1ubuntu1.1 -fPIC -Os) */

module la_drsync(clk, in, nreset, out);
  input clk;
  wire clk;
  input in;
  wire in;
  input nreset;
  wire nreset;
  output out;
  wire out;
  wire \shiftreg[0] ;
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_2 \out_$_DFF_PN0__Q  (
    .CLK(clk),
    .D(\shiftreg[0] ),
    .Q(out),
    .RN(nreset)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_2 \shiftreg_$_DFF_PN0__Q  (
    .CLK(clk),
    .D(in),
    .Q(\shiftreg[0] ),
    .RN(nreset)
  );
endmodule
