/* Generated by Yosys 0.37 (git sha1 a5c7f69ed, clang 14.0.0-1ubuntu1.1 -fPIC -Os) */

module la_dffqn(d, clk, qn);
  input clk;
  wire clk;
  input d;
  wire d;
  output qn;
  wire qn;
  wire \qn_$_DFF_P__Q_D ;
  gf180mcu_fd_sc_mcu7t5v0__clkinv_2 _0_ (
    .I(d),
    .ZN(\qn_$_DFF_P__Q_D )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_2 \qn_$_DFF_P__Q  (
    .CLK(clk),
    .D(\qn_$_DFF_P__Q_D ),
    .Q(qn)
  );
endmodule
