/* Generated by Yosys 0.37 (git sha1 a5c7f69ed, clang 14.0.0-1ubuntu1.1 -fPIC -Os) */

module la_buf(a, z);
  input a;
  wire a;
  output z;
  wire z;
  BUFx2_ASAP7_75t_R _0_ (
    .A(a),
    .Y(z)
  );
endmodule
