/* Generated by Yosys 0.37 (git sha1 a5c7f69ed, clang 14.0.0-1ubuntu1.1 -fPIC -Os) */

module la_clkicgor(clk, te, en, eclk);
  wire _0_;
  input clk;
  wire clk;
  output eclk;
  wire eclk;
  input en;
  wire en;
  wire en_stable;
  input te;
  wire te;
  wire \te_$_OR__A_Y ;
  INVx2_ASAP7_75t_R _1_ (
    .A(clk),
    .Y(_0_)
  );
  NAND2x1_ASAP7_75t_R _2_ (
    .A(_0_),
    .B(en_stable),
    .Y(eclk)
  );
  OR2x2_ASAP7_75t_R _3_ (
    .A(te),
    .B(en),
    .Y(\te_$_OR__A_Y )
  );
  DHLx1_ASAP7_75t_R en_stable_DHLx1_ASAP7_75t_R_Q (
    .CLK(clk),
    .D(\te_$_OR__A_Y ),
    .Q(en_stable)
  );
endmodule
