/* Generated by Yosys 0.37 (git sha1 a5c7f69ed, clang 14.0.0-1ubuntu1.1 -fPIC -Os) */

module la_dffsqn(d, clk, nset, qn);
  wire _0_;
  wire _1_;
  wire _2_;
  input clk;
  wire clk;
  input d;
  wire d;
  input nset;
  wire nset;
  output qn;
  wire qn;
  wire \qn_$_DFF_PN0__Q_D ;
  INVx2_ASAP7_75t_R _3_ (
    .A(nset),
    .Y(_1_)
  );
  INVx2_ASAP7_75t_R _4_ (
    .A(_0_),
    .Y(qn)
  );
  INVx2_ASAP7_75t_R _5_ (
    .A(d),
    .Y(\qn_$_DFF_PN0__Q_D )
  );
  TIELOx1_ASAP7_75t_R _6_ (
    .L(_2_)
  );
  ASYNC_DFFHx1_ASAP7_75t_R \qn_$_DFF_PN0__Q  (
    .CLK(clk),
    .D(\qn_$_DFF_PN0__Q_D ),
    .QN(_0_),
    .RESET(_1_),
    .SET(_2_)
  );
endmodule
