/* Generated by Yosys 0.37 (git sha1 a5c7f69ed, clang 14.0.0-1ubuntu1.1 -fPIC -Os) */

module la_drsync(clk, in, nreset, out);
  wire _0_;
  wire _1_;
  wire _2_;
  wire _3_;
  input clk;
  wire clk;
  input in;
  wire in;
  input nreset;
  wire nreset;
  output out;
  wire out;
  wire \shiftreg[0] ;
  INVx2_ASAP7_75t_R _4_ (
    .A(nreset),
    .Y(_2_)
  );
  INVx2_ASAP7_75t_R _5_ (
    .A(_0_),
    .Y(out)
  );
  INVx2_ASAP7_75t_R _6_ (
    .A(_1_),
    .Y(\shiftreg[0] )
  );
  TIELOx1_ASAP7_75t_R _7_ (
    .L(_3_)
  );
  ASYNC_DFFHx1_ASAP7_75t_R \out_$_DFF_PN0__Q  (
    .CLK(clk),
    .D(\shiftreg[0] ),
    .QN(_0_),
    .RESET(_2_),
    .SET(_3_)
  );
  ASYNC_DFFHx1_ASAP7_75t_R \shiftreg_$_DFF_PN0__Q  (
    .CLK(clk),
    .D(in),
    .QN(_1_),
    .RESET(_2_),
    .SET(_3_)
  );
endmodule
