/* Generated by Yosys 0.37 (git sha1 a5c7f69ed, clang 14.0.0-1ubuntu1.1 -fPIC -Os) */

module la_latq(d, clk, q);
  input clk;
  wire clk;
  input d;
  wire d;
  output q;
  wire q;
  DHLx1_ASAP7_75t_R q_DHLx1_ASAP7_75t_R_Q (
    .CLK(clk),
    .D(d),
    .Q(q)
  );
endmodule
