/* Generated by Yosys 0.37 (git sha1 a5c7f69ed, clang 14.0.0-1ubuntu1.1 -fPIC -Os) */

module la_sdffq(d, si, se, clk, q);
  wire _0_;
  wire _1_;
  wire _2_;
  wire _3_;
  input clk;
  wire clk;
  input d;
  wire d;
  output q;
  wire q;
  wire \q_$_DFF_P__Q_D ;
  input se;
  wire se;
  input si;
  wire si;
  INVx2_ASAP7_75t_R _4_ (
    .A(clk),
    .Y(_1_)
  );
  INVx2_ASAP7_75t_R _5_ (
    .A(_0_),
    .Y(q)
  );
  INVx2_ASAP7_75t_R _6_ (
    .A(se),
    .Y(_2_)
  );
  AND2x4_ASAP7_75t_R _7_ (
    .A(si),
    .B(se),
    .Y(_3_)
  );
  AO21x1_ASAP7_75t_R _8_ (
    .A1(d),
    .A2(_2_),
    .B(_3_),
    .Y(\q_$_DFF_P__Q_D )
  );
  DFFLQNx2_ASAP7_75t_R \q_$_DFF_P__Q  (
    .CLK(_1_),
    .D(\q_$_DFF_P__Q_D ),
    .QN(_0_)
  );
endmodule
