/* Generated by Yosys 0.37 (git sha1 a5c7f69ed, clang 14.0.0-1ubuntu1.1 -fPIC -Os) */

module la_tielo(z);
  wire _0_;
  output z;
  wire z;
  TIELOx1_ASAP7_75t_R _1_ (
    .L(_0_)
  );
  BUFx2_ASAP7_75t_R _2_ (
    .A(_0_),
    .Y(z)
  );
endmodule
