/* Generated by Yosys 0.37 (git sha1 a5c7f69ed, clang 14.0.0-1ubuntu1.1 -fPIC -Os) */

module la_dffq(d, clk, q);
  input clk;
  wire clk;
  input d;
  wire d;
  output q;
  wire q;
  gf180mcu_fd_sc_mcu9t5v0__dffq_2 \q_$_DFF_P__Q  (
    .CLK(clk),
    .D(d),
    .Q(q)
  );
endmodule
