/* Generated by Yosys 0.37 (git sha1 a5c7f69ed, clang 14.0.0-1ubuntu1.1 -fPIC -Os) */

module la_dffrq(d, clk, nreset, q);
  input clk;
  wire clk;
  input d;
  wire d;
  input nreset;
  wire nreset;
  output q;
  wire q;
  gf180mcu_fd_sc_mcu9t5v0__dffrnq_2 \q_$_DFF_PN0__Q  (
    .CLK(clk),
    .D(d),
    .Q(q),
    .RN(nreset)
  );
endmodule
