/* Generated by Yosys 0.37 (git sha1 a5c7f69ed, clang 14.0.0-1ubuntu1.1 -fPIC -Os) */

module la_sdffrqn(d, si, se, clk, nreset, qn);
  wire _0_;
  input clk;
  wire clk;
  input d;
  wire d;
  input nreset;
  wire nreset;
  output qn;
  wire qn;
  wire \qn_$_DFF_PN1__Q_D ;
  input se;
  wire se;
  input si;
  wire si;
  gf180mcu_fd_sc_mcu9t5v0__mux2_2 _1_ (
    .I0(d),
    .I1(si),
    .S(se),
    .Z(_0_)
  );
  gf180mcu_fd_sc_mcu9t5v0__clkinv_2 _2_ (
    .I(_0_),
    .ZN(\qn_$_DFF_PN1__Q_D )
  );
  gf180mcu_fd_sc_mcu9t5v0__dffsnq_2 \qn_$_DFF_PN1__Q  (
    .CLK(clk),
    .D(\qn_$_DFF_PN1__Q_D ),
    .Q(qn),
    .SETN(nreset)
  );
endmodule
