/* Generated by Yosys 0.37 (git sha1 a5c7f69ed, clang 14.0.0-1ubuntu1.1 -fPIC -Os) */

module la_tielo(z);
  wire _0_;
  output z;
  wire z;
  gf180mcu_fd_sc_mcu9t5v0__tiel _1_ (
    .ZN(_0_)
  );
  gf180mcu_fd_sc_mcu9t5v0__buf_4 _2_ (
    .I(_0_),
    .Z(z)
  );
endmodule
