/* Generated by Yosys 0.37 (git sha1 a5c7f69ed, clang 14.0.0-1ubuntu1.1 -fPIC -Os) */

module la_csa32(a, b, c, sum, carry);
  input a;
  wire a;
  input b;
  wire b;
  input c;
  wire c;
  output carry;
  wire carry;
  output sum;
  wire sum;
  FA_X1 sum_FA_X1_S (
    .A(a),
    .B(b),
    .CI(c),
    .CO(carry),
    .S(sum)
  );
endmodule
