/* Generated by Yosys 0.37 (git sha1 a5c7f69ed, clang 14.0.0-1ubuntu1.1 -fPIC -Os) */

module la_clkmux4(clk0, clk1, clk2, clk3, sel0, sel1, sel2, sel3, nreset, out);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  input clk0;
  wire clk0;
  input clk1;
  wire clk1;
  input clk2;
  wire clk2;
  input clk3;
  wire clk3;
  wire \idrsync[0].in ;
  wire \idrsync[0].out ;
  wire \idrsync[0].shiftreg[0] ;
  wire \idrsync[1].in ;
  wire \idrsync[1].out ;
  wire \idrsync[1].shiftreg[0] ;
  wire \idrsync[2].in ;
  wire \idrsync[2].out ;
  wire \idrsync[2].shiftreg[0] ;
  wire \idrsync[3].in ;
  wire \idrsync[3].out ;
  wire \idrsync[3].shiftreg[0] ;
  wire \iensync.z ;
  wire \igate[0].en_stable ;
  wire \igate[1].en_stable ;
  wire \igate[2].en_stable ;
  wire \igate[3].en_stable ;
  input nreset;
  wire nreset;
  output out;
  wire out;
  input sel0;
  wire sel0;
  input sel1;
  wire sel1;
  input sel2;
  wire sel2;
  input sel3;
  wire sel3;
  INV_X1 _14_ (
    .A(sel0),
    .ZN(_00_)
  );
  OR4_X2 _15_ (
    .A1(_00_),
    .A2(\idrsync[1].out ),
    .A3(\idrsync[2].out ),
    .A4(\idrsync[3].out ),
    .ZN(\idrsync[0].in )
  );
  INV_X1 _16_ (
    .A(\idrsync[0].out ),
    .ZN(_01_)
  );
  INV_X1 _17_ (
    .A(sel1),
    .ZN(_02_)
  );
  NOR4_X1 _18_ (
    .A1(\idrsync[2].out ),
    .A2(\idrsync[3].out ),
    .A3(_01_),
    .A4(_02_),
    .ZN(\idrsync[1].in )
  );
  INV_X1 _19_ (
    .A(sel2),
    .ZN(_03_)
  );
  NOR4_X1 _20_ (
    .A1(\idrsync[1].out ),
    .A2(\idrsync[3].out ),
    .A3(_01_),
    .A4(_03_),
    .ZN(\idrsync[2].in )
  );
  INV_X1 _21_ (
    .A(sel3),
    .ZN(_04_)
  );
  NOR4_X1 _22_ (
    .A1(\idrsync[1].out ),
    .A2(\idrsync[2].out ),
    .A3(_04_),
    .A4(\iensync.z ),
    .ZN(\idrsync[3].in )
  );
  AOI22_X1 _23_ (
    .A1(\igate[0].en_stable ),
    .A2(clk0),
    .B1(\igate[2].en_stable ),
    .B2(clk2),
    .ZN(_05_)
  );
  AOI22_X1 _24_ (
    .A1(\igate[1].en_stable ),
    .A2(clk1),
    .B1(\igate[3].en_stable ),
    .B2(clk3),
    .ZN(_06_)
  );
  NAND2_X1 _25_ (
    .A1(_05_),
    .A2(_06_),
    .ZN(out)
  );
  DFFR_X1 \idrsync[0].out_$_DFF_PN0__Q  (
    .CK(clk0),
    .D(\idrsync[0].shiftreg[0] ),
    .Q(\idrsync[0].out ),
    .QN(\iensync.z ),
    .RN(nreset)
  );
  DFFR_X1 \idrsync[0].shiftreg_$_DFF_PN0__Q  (
    .CK(clk0),
    .D(\idrsync[0].in ),
    .Q(\idrsync[0].shiftreg[0] ),
    .QN(_08_),
    .RN(nreset)
  );
  DFFR_X1 \idrsync[1].out_$_DFF_PN0__Q  (
    .CK(clk1),
    .D(\idrsync[1].shiftreg[0] ),
    .Q(\idrsync[1].out ),
    .QN(_10_),
    .RN(nreset)
  );
  DFFR_X1 \idrsync[1].shiftreg_$_DFF_PN0__Q  (
    .CK(clk1),
    .D(\idrsync[1].in ),
    .Q(\idrsync[1].shiftreg[0] ),
    .QN(_09_),
    .RN(nreset)
  );
  DFFR_X1 \idrsync[2].out_$_DFF_PN0__Q  (
    .CK(clk2),
    .D(\idrsync[2].shiftreg[0] ),
    .Q(\idrsync[2].out ),
    .QN(_12_),
    .RN(nreset)
  );
  DFFR_X1 \idrsync[2].shiftreg_$_DFF_PN0__Q  (
    .CK(clk2),
    .D(\idrsync[2].in ),
    .Q(\idrsync[2].shiftreg[0] ),
    .QN(_11_),
    .RN(nreset)
  );
  DFFR_X1 \idrsync[3].out_$_DFF_PN0__Q  (
    .CK(clk3),
    .D(\idrsync[3].shiftreg[0] ),
    .Q(\idrsync[3].out ),
    .QN(_07_),
    .RN(nreset)
  );
  DFFR_X1 \idrsync[3].shiftreg_$_DFF_PN0__Q  (
    .CK(clk3),
    .D(\idrsync[3].in ),
    .Q(\idrsync[3].shiftreg[0] ),
    .QN(_13_),
    .RN(nreset)
  );
  DLL_X1 \igate[0].en_stable_DLL_X1_Q  (
    .D(\iensync.z ),
    .GN(clk0),
    .Q(\igate[0].en_stable )
  );
  DLL_X1 \igate[1].en_stable_DLL_X1_Q  (
    .D(\idrsync[1].out ),
    .GN(clk1),
    .Q(\igate[1].en_stable )
  );
  DLL_X1 \igate[2].en_stable_DLL_X1_Q  (
    .D(\idrsync[2].out ),
    .GN(clk2),
    .Q(\igate[2].en_stable )
  );
  DLL_X1 \igate[3].en_stable_DLL_X1_Q  (
    .D(\idrsync[3].out ),
    .GN(clk3),
    .Q(\igate[3].en_stable )
  );
endmodule
