/* Generated by Yosys 0.37 (git sha1 a5c7f69ed, clang 14.0.0-1ubuntu1.1 -fPIC -Os) */

module la_iddr(clk, in, outrise, outfall);
  wire _0_;
  wire _1_;
  wire _2_;
  input clk;
  wire clk;
  input in;
  wire in;
  wire inrise;
  output outfall;
  wire outfall;
  output outrise;
  wire outrise;
  INV_X1 _3_ (
    .A(clk),
    .ZN(_0_)
  );
  DFF_X1 \inrise_$_DFF_P__Q  (
    .CK(clk),
    .D(in),
    .Q(inrise),
    .QN(_1_)
  );
  DFF_X1 \outfall_$_DFF_N__Q  (
    .CK(_0_),
    .D(in),
    .Q(outfall),
    .QN(_2_)
  );
  DLL_X1 outrise_DLL_X1_Q (
    .D(inrise),
    .GN(clk),
    .Q(outrise)
  );
endmodule
