/* Generated by Yosys 0.37 (git sha1 a5c7f69ed, clang 14.0.0-1ubuntu1.1 -fPIC -Os) */

module la_oddr(clk, in0, in1, out);
  input clk;
  wire clk;
  input in0;
  wire in0;
  input in1;
  wire in1;
  wire in1_sh;
  output out;
  wire out;
  MUX2_X1 _0_ (
    .A(in0),
    .B(in1_sh),
    .S(clk),
    .Z(out)
  );
  DLL_X1 in1_sh_DLL_X1_Q (
    .D(in1),
    .GN(clk),
    .Q(in1_sh)
  );
endmodule
