/* Generated by Yosys 0.37 (git sha1 a5c7f69ed, clang 14.0.0-1ubuntu1.1 -fPIC -Os) */

module la_pwrbuf(vdd, vss, a, z);
  input a;
  wire a;
  input vdd;
  wire vdd;
  input vss;
  wire vss;
  output z;
  wire z;
  BUF_X1 _0_ (
    .A(a),
    .Z(z)
  );
endmodule
