/* Generated by Yosys 0.37 (git sha1 a5c7f69ed, clang 14.0.0-1ubuntu1.1 -fPIC -Os) */

module la_sdffq(d, si, se, clk, q);
  wire _0_;
  input clk;
  wire clk;
  input d;
  wire d;
  output q;
  wire q;
  wire \q_$_DFF_P__Q_D ;
  input se;
  wire se;
  input si;
  wire si;
  MUX2_X1 _1_ (
    .A(d),
    .B(si),
    .S(se),
    .Z(\q_$_DFF_P__Q_D )
  );
  DFF_X1 \q_$_DFF_P__Q  (
    .CK(clk),
    .D(\q_$_DFF_P__Q_D ),
    .Q(q),
    .QN(_0_)
  );
endmodule
